class_names:
- ripe_strawberry
- halfripe_Strawberry
- unripe_Strawberry
data:
  train:
    ann_path: /home/coffeeginu/perception_datasets/891b9546-6b51-4c36-9076-d9727e065238/Dataset5c67cdeb-b415-4f68-8b1b-f08a13ebdd03/coco_labels.json
    img_path: /home/coffeeginu/perception_datasets/891b9546-6b51-4c36-9076-d9727e065238/RGB14541f74-3f32-458f-9c6d-9e2031d534f2/
    input_size:
    - 592
    - 444
    keep_ratio: true
    name: CocoDataset
    pipeline:
      brightness: 0.2
      contrast:
      - 0.8
      - 1.2
      flip: 0.5
      normalize:
      - - 103.53
        - 116.28
        - 123.675
      - - 57.375
        - 57.12
        - 58.395
      perspective: 0.0
      rotation: 0
      saturation:
      - 0.8
      - 1.2
      scale:
      - 0.6
      - 1.4
      shear: 0
      stretch:
      - - 1
        - 1
      - - 1
        - 1
      translate: 0.2
  val:
    ann_path: /home/coffeeginu/perception_datasets/891b9546-6b51-4c36-9076-d9727e065238/Dataset5c67cdeb-b415-4f68-8b1b-f08a13ebdd03/coco_labels.json
    img_path: /home/coffeeginu/perception_datasets/891b9546-6b51-4c36-9076-d9727e065238/RGB14541f74-3f32-458f-9c6d-9e2031d534f2/
    input_size:
    - 592
    - 444
    keep_ratio: true
    name: CocoDataset
    pipeline:
      normalize:
      - - 103.53
        - 116.28
        - 123.675
      - - 57.375
        - 57.12
        - 58.395
device: {}
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP
log:
  interval: 10
model:
  arch:
    backbone:
      activation: LeakyReLU
      model_size: 1.0x
      name: ShuffleNetV2
      out_stages:
      - 2
      - 3
      - 4
    fpn:
      in_channels:
      - 116
      - 232
      - 464
      name: PAN
      num_outs: 3
      out_channels: 96
      start_level: 0
    head:
      feat_channels: 96
      input_channel: 96
      loss:
        loss_bbox:
          loss_weight: 2.0
          name: GIoULoss
        loss_dfl:
          loss_weight: 0.25
          name: DistributionFocalLoss
        loss_qfl:
          beta: 2.0
          loss_weight: 1.0
          name: QualityFocalLoss
          use_sigmoid: true
      name: NanoDetHead
      norm_cfg:
        type: BN
      num_classes: 3
      octave_base_scale: 5
      reg_max: 7
      scales_per_octave: 1
      share_cls_reg: true
      stacked_convs: 2
      strides:
      - 8
      - 16
      - 32
    name: OneStageDetector
save_dir: workspace/nanodet_m
schedule:
  lr_schedule:
    gamma: 0.1
    milestones:
    - 130
    - 160
    - 175
    - 185
    name: MultiStepLR
  optimizer:
    lr: 0.14
    momentum: 0.9
    name: SGD
    weight_decay: 0.0001
  total_epochs: 100
  val_intervals: 10
  warmup:
    name: linear
    ratio: 0.1
    steps: 300
test: {}
